### ISSUE TITLE
Issue with pcl wheel in my machine 

### ISSUE THREAD

**Issue by SebsBarbas** [ori-drs/digiforest_drs#20]
Hi,
I am having issues installing the python wheel for PCL. I wanted to know where are the system requirements needed to be able to run the scripts. 

The error I have is, once downloaded the python_pcl wheel with:
```gdown https://drive.google.com/uc?id=1zv2OO3tSRGvyNLqUt-R-gJYHAwodA3wW```

I do the following command:
```pip install python_pcl-0.3.0rc1-cp38-cp38-linux_x86_64.whl && rm python_pcl-0.3.0rc1-cp38-cp38-linux_x86_64.whl```

But I get the following error:
```ERROR: python_pcl-0.3.0rc1-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.```

Could you help me solve the issue, where can I find other wheels for the same library? Thanks in advance,
Sebastian

**Comment by mauricefallon** [comment]
@benoit-robotics  @mmattamala ,
Can you respond to @SebsBarbas on this?


Sebastian:
Our goal is to remove the need for python_pcl as the project's github repo has been archived

**Comment by mmattamala** [comment]
Hi @SebsBarbas , sorry for the issues, python-pcl is currently not required to run the default algorithms in the scripts. You should be able to test the repo anyways if you don't install it.

On my side, I'll update the README and will remove the dependencies and references to python-pcl, as it was experimental.

**Comment by mmattamala** [comment]
@SebsBarbas I just merged the fix. I'll close the issue for now, but feel free to reopen it you find any problems.

**Comment by SebsBarbas** [comment]
@mmattamala thanks for the help. I will pull again and tests
